export const ActionType = {
  ADD_ELEMENT: "ADD_ELEMENT",
  SET_COMPONENT_TYPE: "SET_COMPONENT_TYPE",
  UPDATE_ELEMENTS: "UPDATE_ELEMENTS",
  SET_ELEMENTS: "SET_ELEMENTS",
  SET_EDITOR_PICKER: "SET_EDITOR_PICKER",
  SELECT_ELEMENT: "SELECT_ELEMENT"
}